/**
 * @file NextAuth catch-all API route.
 * @description Re-exports the GET and POST handlers generated by
 * the NextAuth configuration so Next.js serves `/api/auth/*`.
 */

import { handlers } from "@/lib/auth";
import { NextResponse, NextRequest } from "next/server";

const { GET: originalGET, POST: originalPOST } = handlers;

export async function GET(request: NextRequest) {
  try {
    const url = new URL(request.url);

    if (url.pathname.endsWith("/signin/credentials")) {
      return NextResponse.redirect(new URL("/login", url).toString());
    }

    return await originalGET(request);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("NextAuth GET handler error:", err);
    throw err;
  }
}

export async function POST(request: NextRequest) {
  try {
    return await originalPOST(request);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("NextAuth POST handler error:", err);
    throw err;
  }
}
