spring:
  application:
    name: server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/isopod}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379

application:
  workspace:
    root: ${WORKSPACE_ROOT:../workspaces}
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000}

server:
  port: 8080
